### ISSUE TITLE
Issues in converting tt.get_program_id` and `tt.get_num_programs` to linalg

### ISSUE THREAD

**Issue by fhossein-quic** [Cambricon/triton-linalg#17]
I'm trying to use triton-linalg tool to lower ttir to linalg, but realized that after conversion, `tt.get_program_id` and `tt.get_num_programs` still remain in the tt dialect and are not lowered to linalg. The add_kernel example shared in the repo's README shows this issue as well:

```
module {
  func.func @add_kernel(%arg0: i64, %arg1: i64, %arg2: i64, %arg3: i32) {
    %c1024 = arith.constant 1024 : index
    %c1024_i32 = arith.constant 1024 : i32
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tt.get_program_id x : i32 
```

I'd also like to know how ops in `Auxilary` and `LinalgExt` Dialect can lowered to LLVM IR? What dialects they can be transformed to?

CC- @sethbrin and @zhangqirui

**Comment by sethbrin** [comment]
- `tt.get_program_id x` is target dependent, so we didn't handle these ops in `triton-linalg`. It can be convert to `gpu.block_id x` under the GPU or omp dialect for CPU.
- `auxilary` can be directly lower to `llvm dialect` as it just bind llvm.ptr to memref desc, while `linalgext` can be lower to `vector or other target dependent dialect`. you may refer to the [codegen dialect overview](https://discourse.llvm.org/t/codegen-dialect-overview/2723) of llvm community
- We are hoping to jointly build the triton + linalg ecosystem with the industry. If you are interested, welcome to make pull requests and discussions.
