### ISSUE TITLE
why not use the opensource triton-shared?

### ISSUE THREAD

**Issue by LakeFeiLiu** [Cambricon/triton-linalg#21]
I noticed that Triton-Linalg and Triton-Shared have similar functionalities. Why wasn't Triton-Linalg developed based on Triton-Shared, instead of creating a separate set from scratch?

**Comment by sethbrin** [comment]
Part of the historical reasons is that when we finished developing Triton-Linalg, Triton-Shared was not yet open-sourced. Initially, when Triton-Shared was open-sourced, we considered whether to merge them, but as the versions evolved, the differences between the two became increasingly significant, so we did not further pursue this. For details, please refer to: https://zhuanlan.zhihu.com/p/706401510.
