### ISSUE TITLE
wrong index

### ISSUE THREAD

**Issue by GoodNight-bye** [Cambricon/triton-linalg#22]
https://github.com/Cambricon/triton-linalg/blob/d090db477f8d0ca67cf8cd220ef39b43de9183f9/lib/Dialect/Triton/Transforms/ExtractMoveBackward.cpp#L1127

iterIndex should be the index of iter_args, Why pass the iterIndex to the getResult()？

**Comment by GoodNight-bye** [comment]
![image](https://github.com/user-attachments/assets/84204979-dc5b-4cb2-a527-05991c9be610)

**Comment by GoodNight-bye** [comment]
correct？

**Comment by sethbrin** [comment]
For the `for` operator, each `iterArgs` corresponds to a specific `result` one-to-one. This statement implies that if the `result` corresponding to a particular `iterArgs` is not used outside the loop, the loop will exit directly. The main reason for this limitation is that such cases are currently rare, so they are not yet supported.

**Comment by GoodNight-bye** [comment]
Thanks for your response, I have generated a TTIR from a triton template kernel in the Torch , but encountered an error while generating the TTSHAREDIR
···
#loc = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":16:0)
module {
  tt.func public @triton_triton_tem_fused_3(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/model/nlp/bert128/test_triton_tem_fused_3.py":16:0), %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/model/nlp/bert128/test_triton_tem_fused_3.py":16:0), %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/model/nlp/bert128/test_triton_tem_fused_3.py":16:0)) attributes {noinline = false} {
    %cst = arith.constant dense<32> : tensor<32x32xi32> loc(#loc1)
    %cst_0 = arith.constant dense<32> : tensor<64x32xi32> loc(#loc1)
    %c768_i32 = arith.constant 768 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %c192_i32 = arith.constant 192 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %cst_1 = arith.constant dense<128> : tensor<64x1xi32> loc(#loc1)
    %cst_2 = arith.constant dense<0.000000e+00> : tensor<64x32xf32> loc(#loc1)
    %cst_3 = arith.constant dense<768> : tensor<1x32xi32> loc(#loc1)
    %cst_4 = arith.constant dense<768> : tensor<64x1xi32> loc(#loc1)
    %cst_5 = arith.constant dense<768> : tensor<32xi32> loc(#loc1)
    %cst_6 = arith.constant dense<128> : tensor<64xi32> loc(#loc1)
    %c8_i32 = arith.constant 8 : i32 loc(#loc1)
    %c32_i32 = arith.constant 32 : i32 loc(#loc1)
    %c64_i32 = arith.constant 64 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.divsi %0, %c192_i32 : i32 loc(#loc3)
    %2 = arith.muli %1, %c8_i32 : i32 loc(#loc4)
    %3 = arith.subi %c2_i32, %2 : i32 loc(#loc5)
    %4 = arith.minsi %3, %c8_i32 : i32 loc(#loc6)
    %5 = arith.remsi %0, %4 : i32 loc(#loc7)
    %6 = arith.addi %2, %5 : i32 loc(#loc8)
    %7 = arith.remsi %0, %c192_i32 : i32 loc(#loc9)
    %8 = arith.divsi %7, %4 : i32 loc(#loc10)
    %9 = arith.muli %6, %c64_i32 : i32 loc(#loc11)
    %10 = tt.make_range {end = 64 : i32, start = 0 : i32} : tensor<64xi32> loc(#loc12)
    %11 = tt.splat %9 : i32 -> tensor<64xi32> loc(#loc13)
    %12 = arith.addi %11, %10 : tensor<64xi32> loc(#loc13)
    %13 = arith.muli %8, %c32_i32 : i32 loc(#loc14)
    %14 = tt.make_range {end = 32 : i32, start = 0 : i32} : tensor<32xi32> loc(#loc15)
    %15 = tt.splat %13 : i32 -> tensor<32xi32> loc(#loc16)
    %16 = arith.addi %15, %14 : tensor<32xi32> loc(#loc16)
    %17 = arith.remsi %12, %cst_6 {tt.contiguity = dense<64> : tensor<1xi32>, tt.divisibility = dense<64> : tensor<1xi32>} : tensor<64xi32> loc(#loc17)
    %18 = arith.remsi %16, %cst_5 {tt.contiguity = dense<32> : tensor<1xi32>, tt.divisibility = dense<32> : tensor<1xi32>} : tensor<32xi32> loc(#loc18)
    %19 = tt.expand_dims %17 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32> loc(#loc19)
    %20 = arith.muli %19, %cst_4 : tensor<64x1xi32> loc(#loc20)
    %21 = tt.expand_dims %14 {axis = 0 : i32} : tensor<32xi32> -> tensor<1x32xi32> loc(#loc21)
    %22 = tt.broadcast %20 : tensor<64x1xi32> -> tensor<64x32xi32> loc(#loc22)
    %23 = tt.broadcast %21 : tensor<1x32xi32> -> tensor<64x32xi32> loc(#loc22)
    %24 = arith.addi %22, %23 : tensor<64x32xi32> loc(#loc22)
    %25 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<64x32x!tt.ptr<f32>> loc(#loc23)
    %26 = tt.addptr %25, %24 : tensor<64x32x!tt.ptr<f32>>, tensor<64x32xi32> loc(#loc23)
    %27 = tt.expand_dims %14 {axis = 1 : i32} : tensor<32xi32> -> tensor<32x1xi32> loc(#loc24)
    %28 = tt.expand_dims %18 {axis = 0 : i32} : tensor<32xi32> -> tensor<1x32xi32> loc(#loc25)
    %29 = arith.muli %28, %cst_3 : tensor<1x32xi32> loc(#loc26)
    %30 = tt.broadcast %27 : tensor<32x1xi32> -> tensor<32x32xi32> loc(#loc27)
    %31 = tt.broadcast %29 : tensor<1x32xi32> -> tensor<32x32xi32> loc(#loc27)
    %32 = arith.addi %30, %31 : tensor<32x32xi32> loc(#loc27)
    %33 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<32x32x!tt.ptr<f32>> loc(#loc28)
    %34 = tt.addptr %33, %32 : tensor<32x32x!tt.ptr<f32>>, tensor<32x32xi32> loc(#loc28)
    %35:3 = scf.for %arg3 = %c0_i32 to %c768_i32 step %c32_i32 iter_args(%arg4 = %cst_2, %arg5 = %26, %arg6 = %34) -> (tensor<64x32xf32>, tensor<64x32x!tt.ptr<f32>>, tensor<32x32x!tt.ptr<f32>>)  : i32 {
      %49 = tt.load %arg5 : tensor<64x32x!tt.ptr<f32>> loc(#loc30)
      %50 = tt.load %arg6 : tensor<32x32x!tt.ptr<f32>> loc(#loc31)
      %51 = tt.dot %49, %50, %arg4 : tensor<64x32xf32> * tensor<32x32xf32> -> tensor<64x32xf32> loc(#loc32)
      %52 = tt.addptr %arg5, %cst_0 : tensor<64x32x!tt.ptr<f32>>, tensor<64x32xi32> loc(#loc33)
      %53 = tt.addptr %arg6, %cst : tensor<32x32x!tt.ptr<f32>>, tensor<32x32xi32> loc(#loc34)
      scf.yield %51, %52, %53 : tensor<64x32xf32>, tensor<64x32x!tt.ptr<f32>>, tensor<32x32x!tt.ptr<f32>> loc(#loc35)
    } loc(#loc29)
    %36 = tt.expand_dims %12 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32> loc(#loc36)
    %37 = tt.expand_dims %16 {axis = 0 : i32} : tensor<32xi32> -> tensor<1x32xi32> loc(#loc37)
    %38 = arith.cmpi slt, %36, %cst_1 : tensor<64x1xi32> loc(#loc38)
    %39 = arith.cmpi slt, %37, %cst_3 : tensor<1x32xi32> loc(#loc39)
    %40 = tt.broadcast %38 : tensor<64x1xi1> -> tensor<64x32xi1> loc(#loc40)
    %41 = tt.broadcast %39 : tensor<1x32xi1> -> tensor<64x32xi1> loc(#loc40)
    %42 = arith.andi %40, %41 : tensor<64x32xi1> loc(#loc40)
    %43 = arith.muli %36, %cst_4 : tensor<64x1xi32> loc(#loc41)
    %44 = tt.broadcast %37 : tensor<1x32xi32> -> tensor<64x32xi32> loc(#loc42)
    %45 = tt.broadcast %43 : tensor<64x1xi32> -> tensor<64x32xi32> loc(#loc42)
    %46 = arith.addi %44, %45 : tensor<64x32xi32> loc(#loc42)
    %47 = tt.splat %arg2 : !tt.ptr<f32> -> tensor<64x32x!tt.ptr<f32>> loc(#loc43)
    %48 = tt.addptr %47, %46 : tensor<64x32x!tt.ptr<f32>>, tensor<64x32xi32> loc(#loc43)
    tt.store %48, %35#0, %42 : tensor<64x32x!tt.ptr<f32>> loc(#loc44)
    tt.return loc(#loc45)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":40:24)
#loc3 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":46:22)
#loc4 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":47:41)
#loc5 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":47:30)
#loc6 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":47:50)
#loc7 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":48:40)
#loc8 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":48:34)
#loc9 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":49:19)
#loc10 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":49:30)
#loc11 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":51:17)
#loc12 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":51:40)
#loc13 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":51:27)
#loc14 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":52:17)
#loc15 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":52:40)
#loc16 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":52:27)
#loc17 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":54:52)
#loc18 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":58:52)
#loc19 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":62:17)
#loc20 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":62:28)
#loc21 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":62:43)
#loc22 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":62:40)
#loc23 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":62:13)
#loc24 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":63:16)
#loc25 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":63:43)
#loc26 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":63:54)
#loc27 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":63:39)
#loc28 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":63:13)
#loc29 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":66:25)
#loc30 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":68:24)
#loc31 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":69:24)
#loc32 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":75:25)
#loc33 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":76:13)
#loc34 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":77:13)
#loc35 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":77:8)
#loc36 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":82:15)
#loc37 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":83:15)
#loc38 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":84:20)
#loc39 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":84:34)
#loc40 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":84:26)
#loc41 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":87:26)
#loc42 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":87:22)
#loc43 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":88:25)
#loc44 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":88:68)
#loc45 = loc("/model/nlp/bert128/test_triton_tem_fused_3.py":88:4)
···
 source triton kernel：
···
    for k in range(K, 0, -BLOCK_K):
        if EVEN_K:
            a = tl.load(A)
            b = tl.load(B)
        else:
            a = tl.load(A, mask=rk[None, :] < k, other=0.)
            b = tl.load(B, mask=rk[:, None] < k, other=0.)
        if B_PROLOGUE_CAST_TYPE is not None:
            b = b.to(B_PROLOGUE_CAST_TYPE)
        acc += tl.dot(a, b, allow_tf32=ALLOW_TF32)
        A += BLOCK_K * stride_ak
        B += BLOCK_K * stride_bk
···
It seems like that ttir is not right
```
%49 = tt.load %arg5 : tensor<64x32x!tt.ptr<f32>> loc(#loc30)
```

**Comment by GoodNight-bye** [comment]
It works, thanks.
