### ISSUE TITLE
 Linalg Dialect To Cambrian hardware instructions

### ISSUE THREAD

**Issue by helloworldstone** [Cambricon/triton-linalg#26]
Hi, all.

From the readme, we can know triton-linalg has successfully supported the Cambricon backend as a front-end representation.

If I write a kernel using python triton, how can this kernel run on Cambrian hardware?

Do you also need to provide a tool to convert Linalg Dialect into instructions that can run on Cambrian hardware?
Or where can I download this tool?

**Comment by sethbrin** [comment]
@helloworldstone  We have provided the Triton Cambricon whl package in the Cambricon SDK, but currently, it is only available for commercial customers to download.

**Comment by helloworldstone** [comment]
@sethbrin Is the Triton Cambricon whl package similar to the triont whl package? After installing the Cambricon whl package, developers can use python triton to develop algorithms and run them directly on Cambricon hardware through jit?

**Comment by helloworldstone** [comment]
@sethbrin Is the Triton Cambricon whl package similar to the triont whl package? After installing the Cambricon whl package, developers can use python triton to develop algorithms and run them directly on Cambricon hardware through jit?

**Comment by sethbrin** [comment]
@helloworldstone Yes, currently, Cambricon's Triton supports all features except those related to NVIDIA hardware.
