### ISSUE TITLE
gather and scatter

### ISSUE THREAD

**Issue by helloworldstone** [Cambricon/triton-linalg#27]
Hi，the readme mentions that triton-linalg LinalgExt supports linalg_ext.gather and linalg_ext.scatter, and load.mlir shows the test case of load gather：
`tt.func @load_gather_1d(%arg0: !tt.ptr<f32>, %arg1: tensor<128xi32>) {`
  `%0 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>>`
 `%1 = tt.addptr %0, %arg1 : tensor<128x!tt.ptr<f32>>, tensor<128xi32>`
  `%2 = tt.load %1 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<128x!tt.ptr<f32>>`
 `tt.return`
`}`

1. What should the test case of scatter (scatter store?)look like?

2. What should the python triton code corresponding to gather and scatter look like? Are there any examples?

3. How are linalg_ext.gather and linalg_ext.scatter implemented in Cambrian hardware? Are there any special Cambrian hardware instructions called?

Thank you!

**Comment by sethbrin** [comment]
> What should the test case of scatter (scatter store?)look like?

The following testcase is scatter store:

```
tt.func @store_scatter_1d(%arg0: !tt.ptr<f32>, %arg1: tensor<128xi32>, %arg2: tensor<128xf32>) {
  %0 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>>
  %1 = tt.addptr %0, %arg1 : tensor<128x!tt.ptr<f32>>, tensor<128xi32>
  tt.store %1, %arg2 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<128x!tt.ptr<f32>>
  tt.return
}
```

> What should the python triton code corresponding to gather and scatter look like? Are there any examples?

To implement operators similar to `torch.gather` and `torch.scatter`, where we load data from user-provided indices, we need to use discrete load and store operations. For example:

```python
    @triton.jit
    def gather(input, indices, output, SIZE: tl.constexpr):
        # Get index.
        index = tl.load(indices + tl.arange(0, SIZE)
        # Load input.
        value = tl.load(input + index)
        # Store result.
        tl.store(output + tl.arange(0, SIZE), value)
```

For more complex examples, you can refer to the [FlagGems](https://github.com/FlagOpen/FlagGems/tree/master/src/flag_gems/ops) repository.

> How are linalg_ext.gather and linalg_ext.scatter implemented in Cambrian hardware? Are there any special Cambrian hardware instructions called?

Yes, Cambricon has specialized hardware instructions for accelerating gather/scatter access.
