### ISSUE TITLE
error: redefinition of symbol named 'transpose_memref' 

### ISSUE THREAD

**Issue by xuel0707** [Cambricon/triton-linalg#4]
1. run the command：**triton-linalg-opt --convert-triton-to-linalg test/Dialect/LinalgExt/ops.mlir**
2. report a error:
<img width="552" alt="33457f86a8d97751fe293091d661f75e" src="https://github.com/Cambricon/triton-linalg/assets/131101770/992594b9-fa91-4ab0-b895-15077bcb3fa6">

**Comment by xuel0707** [comment]
1. python3 ./triton-mlu-examples/add.py, to generate: add.ttir, in the path:$HOME/.triton/cache/eb94d36b18eabb943d62528aa76a9b05;
2.  triton-linalg-opt --convert-triton-to-linalg add.ttir, report a error as following:
<img width="396" alt="2bffa900f9b3089163391ba75503db2d" src="https://github.com/Cambricon/triton-linalg/assets/131101770/9cd0adc9-a7e4-4f1b-92d8-ae9c9954de51">

**Comment by xuel0707** [comment]
@sethbrin please have a look and fix it!

**Comment by Artorias123** [comment]
需要添加一个-split-input-file配置项，这个文件里有不止一个这个名字的func，所以需要添加这个配置项

**Comment by xuel0707** [comment]
> 需要添加一个-split-input-file配置项，这个文件里有不止一个这个名字的func，所以需要添加这个配置项

OK，thx.
![image](https://github.com/Cambricon/triton-linalg/assets/131101770/cbb85d6a-be31-41e3-906b-06a2b6ce5443)

**Comment by xuel0707** [comment]
> 1. **python3 ./triton-mlu-examples/add.py**, to generate: add.ttir, in the path:$HOME/.triton/cache/eb94d36b18eabb943d62528aa76a9b05;
> 2. **triton-linalg-opt --convert-triton-to-linalg add.ttir**, report a error as following:
> 
> <img alt="2bffa900f9b3089163391ba75503db2d" width="396" src="https://private-user-images.githubusercontent.com/131101770/338483994-9cd0adc9-a7e4-4f1b-92d8-ae9c9954de51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA2NTIsIm5iZiI6MTcxODE2MDM1MiwicGF0aCI6Ii8xMzExMDE3NzAvMzM4NDgzOTk0LTljZDBhZGM5LWE3ZTQtNGYxYi05MmQ4LWFlOWM5OTU0ZGU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjQ1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTBiMmMxMWFkYjA3MDg5YTE4ZmYyMjQxODFjOGMzYWZjMDBjNWQyZDc5MjYzYjJkN2NkMDAyZTA5MWNlMjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zxj9D-cVxsJ3uiGRmZmNdSEC3fZ0DJmfCEpoFC-XspU">

@Artorias123 can you have a try，the content of add.ttir is as following：
module {
  tt.func public @add_0d1d2d3d(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    %3 = tt.splat %1 : (i32) -> tensor<1024xi32>
    %4 = arith.addi %3, %2 : tensor<1024xi32>
    %5 = tt.splat %arg3 : (i32) -> tensor<1024xi32>
    %6 = arith.cmpi slt, %4, %5 : tensor<1024xi32>
    %7 = tt.splat %arg0 : (!tt.ptr<f32>) -> tensor<1024x!tt.ptr<f32>>
    %8 = tt.addptr %7, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
    %9 = tt.load %8, %6 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<1024xf32>
    %10 = tt.splat %arg1 : (!tt.ptr<f32>) -> tensor<1024x!tt.ptr<f32>>
    %11 = tt.addptr %10, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
    %12 = tt.load %11, %6 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<1024xf32>
    %13 = arith.addf %9, %12 : tensor<1024xf32>
    %14 = tt.splat %arg2 : (!tt.ptr<f32>) -> tensor<1024x!tt.ptr<f32>>
    %15 = tt.addptr %14, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
    tt.store %15, %13, %6 {cache = 1 : i32, evict = 1 : i32} : tensor<1024xf32>
    tt.return
  }
}

**Comment by Artorias123** [comment]
不好意思，看不见你的报错，我这里直接复制这段ir测试，报错是ir的格式错误，似乎这个ir并不是由我们依赖的triton版本生成的？triton原生的ir在不同版本改动较多，可能出现不同版本的ir无法正确识别的问题

**Comment by xuel0707** [comment]
> 不好意思，看不见你的报错，我这里直接复制这段ir测试，报错是ir的格式错误，似乎这个ir并不是由我们依赖的triton版本生成的？triton原生的ir在不同版本改动较多，可能出现不同版本的ir无法正确识别的问题

OK,will close the issue.
