### ISSUE TITLE
[Bufferization]: one-shot bufferization illegal

### ISSUE THREAD

**Issue by YeBug** [Cambricon/triton-linalg#5]
In class`TritonScatteredStoreOpConversion`, func`matchAndRewrite`
![image](https://github.com/Cambricon/triton-linalg/assets/37695448/05923360-5aa7-4795-b815-743efd7398d8)
`bufferization::ToTensorOp` not set restrict and writable, after convert to linalg mlir, this `bufferization.to_tensor` Op is illegal when using one-shot bufferization.
Wonder why ScatteredLoadOp has the restric and writable attribute but ScatteredStoreOp hasn't ?

**Comment by Artorias123** [comment]
这个应该是两个true的，这样改没问题，我这边确认一下，之后会提一个pr修复这个问题

**Comment by Artorias123** [comment]
https://github.com/Cambricon/triton-linalg/pull/10
修复已经提交RP，感谢反馈。
